export interface Testimonial {
  id: string;
  name: string;
  role: string;
  company: string;
  industry: string;
  solutionSlug: string;
  solutionLabel: string;
  rating: number;
  review: string;
  metric?: string;
  initials: string;
  verified: boolean;
  avatar?: string;
}

export const allTestimonials: Testimonial[] = [
  {
    id: "rajesh-kumar",
    name: "Rajesh Kumar",
    role: "Operations Director",
    company: "PrecisionMfg Industries",
    industry: "Manufacturing",
    solutionSlug: "custom-software-development",
    solutionLabel: "Custom Software Development",
    rating: 5,
    metric: "40% Procurement Errors Reduced",
    initials: "RK",
    verified: true,
    review: "Smatal built us a centralized supply chain portal that replaced 3 disconnected tools. Our procurement team's turnaround time improved dramatically and manual reconciliation errors are virtually eliminated.",
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    role: "Chief Technology Officer",
    company: "FinClaim Solutions",
    industry: "Finance",
    solutionSlug: "custom-software-development",
    solutionLabel: "Custom Software Development",
    rating: 5,
    metric: "10-Day Cycle → 48 Hours",
    initials: "PS",
    verified: true,
    review: "We went from a 10-day insurance claims cycle down to 48 hours. Smatal truly understood the regulatory compliance nuances and delivered well ahead of schedule.",
  },
  {
    id: "anita-menon",
    name: "Dr. Anita Menon",
    role: "Managing Director",
    company: "CareFirst Clinics",
    industry: "Healthcare",
    solutionSlug: "web-development",
    solutionLabel: "Web Development",
    rating: 5,
    metric: "300% Online Bookings Growth",
    initials: "AM",
    verified: true,
    review: "Our multi-location clinic portal completely transformed patient onboarding. Direct appointment bookings tripled in 90 days and we rank on page one for 18 medical keywords in Chennai.",
  },
  {
    id: "vikram-nair",
    name: "Vikram Nair",
    role: "Senior Partner",
    company: "Nair & Associates Legal",
    industry: "Professional Services",
    solutionSlug: "web-development",
    solutionLabel: "Web Development",
    rating: 5,
    metric: "2.5x Client Lead Volume",
    initials: "VN",
    verified: true,
    review: "Smatal understood that our legal portal needed to project absolute credibility and security. The web application is fast, elegant, and converted high-value corporate retainers from week one.",
  },
  {
    id: "arjun-mehta",
    name: "Arjun Mehta",
    role: "Head of Logistics",
    company: "SwiftLogix Transport",
    industry: "Logistics",
    solutionSlug: "mobile-app-development",
    solutionLabel: "Mobile App Development",
    rating: 5,
    metric: "2h → 10min Job Status Reporting",
    initials: "AM",
    verified: true,
    review: "Our field technicians went from paper bills to a mobile app in 12 weeks. Real-time GPS waypoints and digital proof-of-delivery improved our customer NPS score by 28 points.",
  },
  {
    id: "sunita-reddy",
    name: "Sunita Reddy",
    role: "CEO & Founder",
    company: "FreshMart Retail",
    industry: "Retail",
    solutionSlug: "mobile-app-development",
    solutionLabel: "Mobile App Development",
    rating: 5,
    metric: "12,000+ First-Month App Users",
    initials: "SR",
    verified: true,
    review: "The loyalty and quick-commerce app Smatal built for us was a massive success. Over 12,000 downloads in month one and customer reorder frequency climbed by 34%.",
  },
  {
    id: "mohammed-farhan",
    name: "Mohammed Farhan",
    role: "Managing Director",
    company: "PrimeCraft Manufacturing",
    industry: "Manufacturing",
    solutionSlug: "erp-solutions",
    solutionLabel: "ERP Solutions",
    rating: 5,
    metric: "Monthly Close: 4 Days → 2 Hours",
    initials: "MF",
    verified: true,
    review: "We replaced 6 disconnected spreadsheets with one unified manufacturing ERP. Monthly reporting that used to take 4 full days now takes 2 hours. The investment paid for itself in the first quarter.",
  },
  {
    id: "kavitha-suresh",
    name: "Kavitha Suresh",
    role: "Head of Operations",
    company: "StyleSelect Retail",
    industry: "Retail",
    solutionSlug: "erp-solutions",
    solutionLabel: "ERP Solutions",
    rating: 5,
    metric: "65% Out-of-Stock Reduction",
    initials: "KS",
    verified: true,
    review: "Inventory stockouts used to cost us substantial revenue during festival seasons. With Smatal's real-time inventory engine, stockouts dropped 65% across our 14 retail branches.",
  },
  {
    id: "rahul-joshi",
    name: "Rahul Joshi",
    role: "Director of Sales",
    company: "PrimeRealty Developers",
    industry: "Real Estate",
    solutionSlug: "crm-solutions",
    solutionLabel: "CRM Solutions",
    rating: 5,
    metric: "₹50 Cr+ Sales Pipeline Visibility",
    initials: "RJ",
    verified: true,
    review: "We went from WhatsApp spreadsheet chaos to a CRM that gives executive visibility into a ₹50 Cr pipeline. Sales lead response time plummeted to under 8 minutes.",
  },
  {
    id: "deepa-krishnan",
    name: "Deepa Krishnan",
    role: "Regional Head",
    company: "SecureLife Financial",
    industry: "Finance",
    solutionSlug: "crm-solutions",
    solutionLabel: "CRM Solutions",
    rating: 5,
    metric: "38% Policy Renewal Rate Increase",
    initials: "DK",
    verified: true,
    review: "Policy renewals were our biggest operational headache. Smatal's CRM automated the entire multi-channel follow-up workflow and lapse rates dropped significantly in Q1.",
  },
  {
    id: "ashwin-pillai",
    name: "Ashwin Pillai",
    role: "Finance Director",
    company: "CloudWorks SaaS",
    industry: "Technology",
    solutionSlug: "billing-solutions",
    solutionLabel: "Billing Solutions",
    rating: 5,
    metric: "40% Failed Payment Recovery",
    initials: "AP",
    verified: true,
    review: "We were manually generating invoices for 500+ subscribers every month. Smatal's automated billing platform solved invoice generation and dunning recovery in one stroke.",
  },
  {
    id: "vijay-ramesh",
    name: "Dr. Vijay Ramesh",
    role: "Medical Director",
    company: "LifeCare Health",
    industry: "Healthcare",
    solutionSlug: "billing-solutions",
    solutionLabel: "Billing Solutions",
    rating: 5,
    metric: "52% Faster Outstanding Collections",
    initials: "VR",
    verified: true,
    review: "Our multi-specialty clinics had a fragmented billing setup with GST reconciliation delays. Smatal unified all billing into a single HIPAA/NABH compliant cloud system.",
  },
  {
    id: "margaret-dsouza",
    name: "Sr. Margaret D'Souza",
    role: "Principal",
    company: "Holy Cross Academy",
    industry: "Education",
    solutionSlug: "school-management",
    solutionLabel: "School Management",
    rating: 5,
    metric: "85% Online Fee Collection Rate",
    initials: "MD",
    verified: true,
    review: "Our 1,200-student school went completely digital in 8 weeks. Parents love paying fees on the mobile app, and our teachers no longer spend hours on manual attendance registers.",
  },
  {
    id: "ravi-shankar",
    name: "Ravi Shankar",
    role: "Managing Director",
    company: "Apex Learning Network",
    industry: "Education",
    solutionSlug: "school-management",
    solutionLabel: "School Management",
    rating: 5,
    metric: "22% Student Outcome Improvement",
    initials: "RS",
    verified: true,
    review: "Managing 3 training centres across Tamil Nadu is seamless now. Attendance, study materials, and tests are managed on one platform that I can monitor from my phone.",
  },
  {
    id: "suresh-natarajan",
    name: "Dr. Suresh Natarajan",
    role: "Chief Executive",
    company: "MedCity Hospitals",
    industry: "Healthcare",
    solutionSlug: "digital-marketing",
    solutionLabel: "Digital Marketing",
    rating: 5,
    metric: "40 → 380 Monthly Consultations",
    initials: "SN",
    verified: true,
    review: "Online doctor appointments surged from 40 to 380 per month within 6 months. The data clarity and ROI tracking Smatal provides is what makes them an indispensable partner.",
  },
  {
    id: "meera-kapoor",
    name: "Meera Kapoor",
    role: "Founder & Creative Director",
    company: "StyleBox Apparel",
    industry: "Retail",
    solutionSlug: "digital-marketing",
    solutionLabel: "Digital Marketing",
    rating: 5,
    metric: "3.2x Return On Ad Spend (ROAS)",
    initials: "MK",
    verified: true,
    review: "Smatal restructured our paid performance marketing and e-commerce conversion funnel. Within 90 days, our monthly online revenue tripled with healthy profit margins.",
  },
  {
    id: "ramesh-iyer",
    name: "Dr. Ramesh Iyer",
    role: "Head of Information Systems",
    company: "CityHealth Systems",
    industry: "Healthcare",
    solutionSlug: "support-maintenance",
    solutionLabel: "Support & Maintenance",
    rating: 5,
    metric: "Zero Outages in 18 Months",
    initials: "RI",
    verified: true,
    review: "We suffered 3 major server crashes with our previous vendor. In 18 months under Smatal's DevOps SLA, we have had zero downtime and sub-minute incident response.",
  },
  {
    id: "kiran-desai",
    name: "Kiran Desai",
    role: "Plant Operations Manager",
    company: "MetalWorks Foundry",
    industry: "Manufacturing",
    solutionSlug: "support-maintenance",
    solutionLabel: "Support & Maintenance",
    rating: 5,
    metric: "12 Custom Features Delivered in 6mo",
    initials: "KD",
    verified: true,
    review: "As our factory scaled, our ERP needed continuous tuning. Smatal's support team optimized database queries and rolled out 12 custom enhancements without disturbing daily shifts.",
  },
];

export function getTestimonialsBySlug(slug: string): Testimonial[] {
  return allTestimonials.filter((t) => t.solutionSlug === slug);
}

export function getFeaturedTestimonials(count = 6): Testimonial[] {
  const picks = ["mohammed-farhan", "anita-menon", "rahul-joshi", "arjun-mehta", "kavitha-suresh", "ashwin-pillai", "margaret-dsouza", "suresh-natarajan"];
  return allTestimonials.filter((t) => picks.includes(t.id)).slice(0, count);
}
