export interface Testimonial {
  id: string;
  name: string;
  role: string;
  company: string;
  industry: string;
  solutionSlug: string;
  solutionLabel: string;
  rating: number;
  review: string;
  avatar: string;
}

export const allTestimonials: Testimonial[] = [
  {
    id: "rajesh-kumar",
    name: "Rajesh Kumar",
    role: "Operations Director",
    company: "PrecisionMfg Industries",
    industry: "Manufacturing",
    solutionSlug: "custom-software-development",
    solutionLabel: "Custom Software Development",
    rating: 5,
    review: "Smatel built us a supply chain portal that replaced 3 different tools. Our procurement team's efficiency has improved dramatically and errors are virtually eliminated.",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    role: "CTO",
    company: "FinClaim Solutions",
    industry: "Finance",
    solutionSlug: "custom-software-development",
    solutionLabel: "Custom Software Development",
    rating: 5,
    review: "We went from a 10-day claims cycle to 48 hours. The team truly understood our domain and delivered beyond expectations.",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "anita-menon",
    name: "Dr. Anita Menon",
    role: "Managing Director",
    company: "CareFirst Clinics",
    industry: "Healthcare",
    solutionSlug: "web-development",
    solutionLabel: "Web Development",
    rating: 5,
    review: "Our new website transformed our patient acquisition. Online bookings tripled in just 3 months and we now rank on the first page for all our key search terms.",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "vikram-nair",
    name: "Vikram Nair",
    role: "Partner",
    company: "Nair & Associates Law",
    industry: "Professional Services",
    solutionSlug: "web-development",
    solutionLabel: "Web Development",
    rating: 5,
    review: "Smatel understood that our website needed to communicate trust. The result was beyond our expectations — elegant, fast, and converting from week one.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "arjun-mehta",
    name: "Arjun Mehta",
    role: "Head of Operations",
    company: "SwiftLogix",
    industry: "Logistics",
    solutionSlug: "mobile-app-development",
    solutionLabel: "Mobile App Development",
    rating: 5,
    review: "Our field technicians went from paper forms to a slick mobile app in 12 weeks. The difference in operational efficiency has been remarkable — our customers love the real-time updates.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "sunita-reddy",
    name: "Sunita Reddy",
    role: "CEO",
    company: "FreshMart Retail",
    industry: "Retail",
    solutionSlug: "mobile-app-development",
    solutionLabel: "Mobile App Development",
    rating: 5,
    review: "The loyalty app Smatel built for us was a game-changer. 12,000 downloads in the first month and our repeat customer numbers are up significantly.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "mohammed-farhan",
    name: "Mohammed Farhan",
    role: "Managing Director",
    company: "PrimeCraft Manufacturing",
    industry: "Manufacturing",
    solutionSlug: "erp-solutions",
    solutionLabel: "ERP Solutions",
    rating: 5,
    review: "We went from 6 disconnected tools to one ERP that our entire team actually uses. Our monthly reporting that used to take 4 days now takes 2 hours. The ROI was clear within the first quarter.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "kavitha-suresh",
    name: "Kavitha Suresh",
    role: "Operations Head",
    company: "StyleSelect Retail",
    industry: "Retail",
    solutionSlug: "erp-solutions",
    solutionLabel: "ERP Solutions",
    rating: 5,
    review: "Inventory stockouts used to cost us lakhs every month. After the Smatel ERP, we have complete visibility and stockouts are down 65%. The system paid for itself in 4 months.",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "rahul-joshi",
    name: "Rahul Joshi",
    role: "Sales Director",
    company: "PrimeRealty Developers",
    industry: "Real Estate",
    solutionSlug: "crm-solutions",
    solutionLabel: "CRM Solutions",
    rating: 5,
    review: "We went from Excel chaos to a CRM that gives me real-time visibility into a ₹50 Cr pipeline. Lead response time is now under 10 minutes. The conversion improvement alone paid for the CRM in one month.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "deepa-krishnan",
    name: "Deepa Krishnan",
    role: "Branch Manager",
    company: "SecureLife Insurance",
    industry: "Finance",
    solutionSlug: "crm-solutions",
    solutionLabel: "CRM Solutions",
    rating: 5,
    review: "Policy renewal was our biggest pain point. Smatel's CRM automated the entire renewal follow-up sequence and our lapse rate dropped dramatically within the first quarter.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "ashwin-pillai",
    name: "Ashwin Pillai",
    role: "Finance Head",
    company: "CloudWorks SaaS",
    industry: "Technology",
    solutionSlug: "billing-solutions",
    solutionLabel: "Billing Solutions",
    rating: 5,
    review: "We had 500 subscribers and we were manually invoicing all of them. Smatel's billing platform automated everything overnight. Churn from billing failures dropped 40% and our finance team finally has time to do real finance work.",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "vijay-ramesh",
    name: "Dr. Vijay Ramesh",
    role: "Medical Director",
    company: "LifeCare Clinics",
    industry: "Healthcare",
    solutionSlug: "billing-solutions",
    solutionLabel: "Billing Solutions",
    rating: 5,
    review: "Our clinics had a billing mess — different systems, GST issues, and unpaid balances everywhere. Smatel centralised everything and our outstanding collections dropped by more than half.",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "margaret-dsouza",
    name: "Sr. Margaret D'Souza",
    role: "Principal",
    company: "Holy Cross Academy",
    industry: "Education",
    solutionSlug: "school-management",
    solutionLabel: "School Management",
    rating: 5,
    review: "Our school went from paper registers and cash fee collection to a fully digital institution in just 8 weeks. Parents love the app. Our teachers love not spending evenings on paperwork. The transformation has been remarkable.",
    avatar: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "ravi-shankar",
    name: "Ravi Shankar",
    role: "Director",
    company: "Apex Coaching Institute",
    industry: "Education",
    solutionSlug: "school-management",
    solutionLabel: "School Management",
    rating: 5,
    review: "Managing 3 centres was a nightmare before. Now everything is in one platform — attendance, tests, materials, and fees. Our student pass rates improved 22% and I can run the institute from anywhere.",
    avatar: "https://images.unsplash.com/photo-1542178243-bc20204b769f?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "suresh-natarajan",
    name: "Dr. Suresh Natarajan",
    role: "CEO",
    company: "MedCity Hospitals",
    industry: "Healthcare",
    solutionSlug: "digital-marketing",
    solutionLabel: "Digital Marketing",
    rating: 5,
    review: "We went from 40 online appointments per month to 380 in 6 months. The ROI clarity that Smatel provides is what separates them from every other agency — we know exactly what every rupee generates.",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "meera-kapoor",
    name: "Meera Kapoor",
    role: "Founder",
    company: "StyleBox Fashion",
    industry: "Retail",
    solutionSlug: "digital-marketing",
    solutionLabel: "Digital Marketing",
    rating: 5,
    review: "Our Instagram organic strategy had plateaued. Smatel launched a proper paid acquisition strategy and within 3 months our monthly revenue had tripled. The ROAS numbers are consistently strong.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "ramesh-iyer",
    name: "Dr. Ramesh Iyer",
    role: "IT Director",
    company: "CityHealth Hospitals",
    industry: "Healthcare",
    solutionSlug: "support-maintenance",
    solutionLabel: "Support & Maintenance",
    rating: 5,
    review: "We had 3 major outages before Smatel took over. In 18 months since, we've had zero. They proactively caught and fixed vulnerabilities we didn't even know existed. Absolute peace of mind.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&h=256&auto=format&fit=crop",
  },
  {
    id: "kiran-desai",
    name: "Kiran Desai",
    role: "Plant Manager",
    company: "MetalWorks Industries",
    industry: "Manufacturing",
    solutionSlug: "support-maintenance",
    solutionLabel: "Support & Maintenance",
    rating: 5,
    review: "Our ERP was getting slower as we grew. Smatel's maintenance team tuned the database and now it's faster than ever. They also delivered 12 improvements our team requested over 6 months.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=256&h=256&auto=format&fit=crop",
  },
];

export function getTestimonialsBySlug(slug: string): Testimonial[] {
  return allTestimonials.filter((t) => t.solutionSlug === slug);
}

export function getFeaturedTestimonials(count = 3): Testimonial[] {
  // Pick diverse testimonials from different solutions
  const picks = ["mohammed-farhan", "anita-menon", "rahul-joshi"];
  return allTestimonials.filter((t) => picks.includes(t.id)).slice(0, count);
}
